// Seed data for local development / demos.
// Replace the *contents* of this file freely — the shapes here are what
// services/api.js and the ML pipeline expect, and mirror the intended
// backend response schema (see README.md → "Wiring a real backend").

export const seedUsers = [
  {
    id: "u1",
    username: "meera_desk",
    displayName: "Meera Krishnan",
    bio: "Fact-checking desk, Chennai. Tamil & English. இது என் இடம்.",
    location: "Chennai, IN",
    avatarColor: "#E89E3D",
    joinedAt: "2023-11-02T00:00:00Z",
    platformVerified: true,
    languages: ["ta", "en"],
    followerCount: 18400,
    followingCount: 312,
  },
  {
    id: "u2",
    username: "arjun.reports",
    displayName: "Arjun Bhatt",
    bio: "Covering Gujarat & Maharashtra. Views mine, sources always linked.",
    location: "Ahmedabad, IN",
    avatarColor: "#4FA7C4",
    joinedAt: "2022-06-14T00:00:00Z",
    platformVerified: true,
    languages: ["gu", "hi", "en"],
    followerCount: 52100,
    followingCount: 890,
  },
  {
    id: "u3",
    username: "ritu_writes",
    displayName: "Ritu Sharma",
    bio: "कविता, समाचार, और थोड़ी बहुत बहस। दिल्ली से।",
    location: "New Delhi, IN",
    avatarColor: "#C4708C",
    joinedAt: "2024-01-20T00:00:00Z",
    platformVerified: false,
    languages: ["hi", "en"],
    followerCount: 3210,
    followingCount: 480,
  },
  {
    id: "u4",
    username: "kolkata_koushik",
    displayName: "Koushik Das",
    bio: "আড্ডা, ফুটবল, আর মাঝেমধ্যে গুজব ধরিয়ে দেওয়া।",
    location: "Kolkata, IN",
    avatarColor: "#6E8F5C",
    joinedAt: "2023-03-09T00:00:00Z",
    platformVerified: false,
    languages: ["bn", "en"],
    followerCount: 8760,
    followingCount: 1200,
  },
  {
    id: "u5",
    username: "priya.codes",
    displayName: "Priya Nair",
    bio: "ML engineer building fake-news classifiers for low-resource Indic languages. This is my test account.",
    location: "Bengaluru, IN",
    avatarColor: "#8C7BC7",
    joinedAt: "2024-08-01T00:00:00Z",
    platformVerified: false,
    languages: ["en", "ml", "hi"],
    followerCount: 940,
    followingCount: 210,
  },
  {
    id: "u6",
    username: "you",
    displayName: "You",
    bio: "Testing the Sāthi frontend prototype.",
    location: "",
    avatarColor: "#D97757",
    joinedAt: "2026-01-01T00:00:00Z",
    platformVerified: false,
    languages: ["en", "hi"],
    followerCount: 12,
    followingCount: 34,
  },
];

// language codes used across the app
export const LANGUAGES = [
  { code: "en", name: "English" },
  { code: "hi", name: "Hindi" },
  { code: "ta", name: "Tamil" },
  { code: "bn", name: "Bengali" },
  { code: "gu", name: "Gujarati" },
  { code: "ml", name: "Malayalam" },
  { code: "mr", name: "Marathi" },
];

const now = Date.now();
const minsAgo = (m) => new Date(now - m * 60000).toISOString();

// verdict: 'real' | 'fake' | 'uncertain'
// status: 'analyzed' | 'processing'
export const seedPosts = [
  {
    id: "p1",
    authorId: "u2",
    parentId: null,
    language: { code: "en", name: "English" },
    content:
      "BREAKING: Govt has NOT announced a new ₹2000 note recall — the circulating screenshot is from a 2023 notice, dates edited. Please verify before forwarding on family WhatsApp groups.",
    media: null,
    createdAt: minsAgo(38),
    stats: { likes: 892, reposts: 401, comments: 3, views: 15200 },
    likedByMe: false,
    repostedByMe: false,
    analysis: {
      status: "analyzed",
      verdict: "real",
      confidence: 0.94,
      model: "IndicBERT-FND v0.4",
      explanation:
        "Claim cross-checked against RBI press releases. No recall notice found for the stated date; the circulating image's metadata matches a 2023 advisory reused with an edited date.",
      matchedClaims: [
        { title: "RBI press release archive", source: "rbi.org.in", stance: "contradicts" },
        { title: "PIB Fact Check thread", source: "pib.gov.in", stance: "supports" },
      ],
    },
  },
  {
    id: "p2",
    authorId: "u3",
    parentId: null,
    language: { code: "hi", name: "Hindi" },
    content:
      "वायरल वीडियो में दिखाया जा रहा है कि नई पेयजल योजना से पूरे गांव को 24 घंटे पानी मिलने लगा — पड़ताल में यह वीडियो दूसरे राज्य का निकला और तीन साल पुराना है।",
    translation:
      "A viral video claims a new water scheme gives an entire village 24-hour water — investigation found the video is from a different state and three years old.",
    media: null,
    createdAt: minsAgo(95),
    stats: { likes: 234, reposts: 88, comments: 2, views: 5400 },
    likedByMe: true,
    repostedByMe: false,
    analysis: {
      status: "analyzed",
      verdict: "fake",
      confidence: 0.88,
      model: "IndicBERT-FND v0.4",
      explanation:
        "Reverse image search on keyframes matches a 2022 upload from a different district. No matching scheme announcement found for the claimed location or date.",
      matchedClaims: [
        { title: "Original 2022 upload (regional news archive)", source: "newsarchive.in", stance: "contradicts" },
      ],
    },
  },
  {
    id: "p3",
    authorId: "u4",
    parentId: null,
    language: { code: "bn", name: "Bengali" },
    content:
      "আজ সকালে হাওড়া ব্রিজে যান চলাচল সাময়িক বন্ধ ছিল রক্ষণাবেক্ষণের কাজের জন্য, বেলা ১১টার মধ্যে স্বাভাবিক হয়ে যায়।",
    translation:
      "Traffic on Howrah Bridge was briefly halted this morning for maintenance work, and returned to normal by 11 AM.",
    media: null,
    createdAt: minsAgo(140),
    stats: { likes: 156, reposts: 22, comments: 1, views: 3100 },
    likedByMe: false,
    repostedByMe: false,
    analysis: {
      status: "analyzed",
      verdict: "real",
      confidence: 0.81,
      model: "IndicBERT-FND v0.4",
      explanation:
        "Matches official Kolkata Traffic Police advisory issued for the same morning window. Timing and location details align.",
      matchedClaims: [
        { title: "Kolkata Traffic Police advisory", source: "kolkatatrafficpolice.gov.in", stance: "supports" },
      ],
    },
  },
  {
    id: "p4",
    authorId: "u5",
    parentId: null,
    language: { code: "en", name: "English" },
    content:
      "Small language model as a triage filter before the full transformer classifier cut our average verification latency by ~40% in testing. Cheap first pass, expensive model only when needed.",
    media: null,
    createdAt: minsAgo(210),
    stats: { likes: 61, reposts: 9, comments: 4, views: 980 },
    likedByMe: false,
    repostedByMe: false,
    analysis: {
      status: "analyzed",
      verdict: "uncertain",
      confidence: 0.52,
      model: "IndicBERT-FND v0.4",
      explanation:
        "Opinion / technical claim about internal system performance — not a verifiable public-interest news claim. Flagged as low-priority for the fact pipeline.",
      matchedClaims: [],
    },
  },
  {
    id: "p5",
    authorId: "u1",
    parentId: null,
    language: { code: "ta", name: "Tamil" },
    content:
      "நாளை முதல் அனைத்து பள்ளிகளுக்கும் விடுமுறை என பரவும் செய்தி தவறானது — கல்வித்துறை இதுவரை எந்த அறிவிப்பும் வெளியிடவில்லை.",
    translation:
      "The message claiming schools are closed from tomorrow is false — the education department has issued no such notice so far.",
    media: null,
    createdAt: minsAgo(260),
    stats: { likes: 1900, reposts: 760, comments: 0, views: 30500 },
    likedByMe: false,
    repostedByMe: true,
    analysis: {
      status: "analyzed",
      verdict: "fake",
      confidence: 0.91,
      model: "IndicBERT-FND v0.4",
      explanation:
        "No corresponding circular found on the state education department portal. Message structure matches prior forwarded-message hoax templates flagged in the training set.",
      matchedClaims: [
        { title: "State education dept. circulars page", source: "tn.gov.in", stance: "contradicts" },
      ],
    },
  },
  {
    id: "p6",
    authorId: "u2",
    parentId: null,
    language: { code: "en", name: "English" },
    content:
      "Testing the live pipeline — posting this right before the demo to show the 'analyzing' state. Ignore me.",
    media: null,
    createdAt: minsAgo(4),
    stats: { likes: 3, reposts: 0, comments: 0, views: 40 },
    likedByMe: false,
    repostedByMe: false,
    analysis: {
      status: "processing",
      verdict: null,
      confidence: null,
      model: "IndicBERT-FND v0.4",
      explanation: "",
      matchedClaims: [],
    },
  },

  // replies to p1
  {
    id: "c1",
    authorId: "u3",
    parentId: "p1",
    language: { code: "en", name: "English" },
    content: "Thank you for this — my uncle forwarded that exact screenshot yesterday.",
    media: null,
    createdAt: minsAgo(30),
    stats: { likes: 44, reposts: 0, comments: 0, views: 900 },
    likedByMe: false,
    repostedByMe: false,
    analysis: { status: "analyzed", verdict: "uncertain", confidence: 0.4, model: "IndicBERT-FND v0.4", explanation: "Personal statement, not a factual claim.", matchedClaims: [] },
  },
  {
    id: "c2",
    authorId: "u5",
    parentId: "p1",
    language: { code: "en", name: "English" },
    content: "Good catch. Any chance you can share the metadata diff? Curious how clean the edit was.",
    media: null,
    createdAt: minsAgo(20),
    stats: { likes: 12, reposts: 0, comments: 0, views: 300 },
    likedByMe: false,
    repostedByMe: false,
    analysis: { status: "analyzed", verdict: "uncertain", confidence: 0.35, model: "IndicBERT-FND v0.4", explanation: "Question, not a factual claim.", matchedClaims: [] },
  },
  {
    id: "c3",
    authorId: "u4",
    parentId: "p1",
    language: { code: "en", name: "English" },
    content: "Reposting this to my family group with a translation, hope that's alright.",
    media: null,
    createdAt: minsAgo(10),
    stats: { likes: 8, reposts: 0, comments: 0, views: 150 },
    likedByMe: false,
    repostedByMe: false,
    analysis: { status: "analyzed", verdict: "uncertain", confidence: 0.3, model: "IndicBERT-FND v0.4", explanation: "Personal statement, not a factual claim.", matchedClaims: [] },
  },
  // replies to p2
  {
    id: "c4",
    authorId: "u1",
    parentId: "p2",
    language: { code: "en", name: "English" },
    content: "Same video was debunked in Tamil Nadu context last year too. It keeps resurfacing.",
    media: null,
    createdAt: minsAgo(70),
    stats: { likes: 30, reposts: 0, comments: 0, views: 500 },
    likedByMe: false,
    repostedByMe: false,
    analysis: { status: "analyzed", verdict: "uncertain", confidence: 0.4, model: "IndicBERT-FND v0.4", explanation: "Personal observation.", matchedClaims: [] },
  },
  {
    id: "c5",
    authorId: "u2",
    parentId: "p2",
    language: { code: "en", name: "English" },
    content: "Classic recycled-video pattern. Worth a thread on how to spot re-uploads.",
    media: null,
    createdAt: minsAgo(60),
    stats: { likes: 19, reposts: 0, comments: 0, views: 400 },
    likedByMe: false,
    repostedByMe: false,
    analysis: { status: "analyzed", verdict: "uncertain", confidence: 0.4, model: "IndicBERT-FND v0.4", explanation: "Opinion / suggestion.", matchedClaims: [] },
  },
  // replies to p4
  {
    id: "c6",
    authorId: "u1",
    parentId: "p4",
    language: { code: "en", name: "English" },
    content: "What's the small model — a distilled classifier or something rule-based first?",
    media: null,
    createdAt: minsAgo(200),
    stats: { likes: 5, reposts: 0, comments: 0, views: 90 },
    likedByMe: false,
    repostedByMe: false,
    analysis: { status: "analyzed", verdict: "uncertain", confidence: 0.3, model: "IndicBERT-FND v0.4", explanation: "Question.", matchedClaims: [] },
  },
  {
    id: "c7",
    authorId: "u5",
    parentId: "p4",
    language: { code: "en", name: "English" },
    content: "Distilled — a few million params, just enough to flag 'probably not news' and skip the heavy model.",
    media: null,
    createdAt: minsAgo(195),
    stats: { likes: 22, reposts: 0, comments: 0, views: 210 },
    likedByMe: false,
    repostedByMe: false,
    analysis: { status: "analyzed", verdict: "uncertain", confidence: 0.3, model: "IndicBERT-FND v0.4", explanation: "Technical explanation.", matchedClaims: [] },
  },
  {
    id: "c8",
    authorId: "u4",
    parentId: "p4",
    language: { code: "en", name: "English" },
    content: "40% latency drop is a great number for a thesis defense slide.",
    media: null,
    createdAt: minsAgo(190),
    stats: { likes: 14, reposts: 0, comments: 0, views: 180 },
    likedByMe: false,
    repostedByMe: false,
    analysis: { status: "analyzed", verdict: "uncertain", confidence: 0.3, model: "IndicBERT-FND v0.4", explanation: "Opinion.", matchedClaims: [] },
  },
  {
    id: "c9",
    authorId: "u3",
    parentId: "p4",
    language: { code: "en", name: "English" },
    content: "Does the triage model handle code-mixed Hindi-English text okay, or does that need its own path?",
    media: null,
    createdAt: minsAgo(180),
    stats: { likes: 9, reposts: 0, comments: 0, views: 140 },
    likedByMe: false,
    repostedByMe: false,
    analysis: { status: "analyzed", verdict: "uncertain", confidence: 0.3, model: "IndicBERT-FND v0.4", explanation: "Question.", matchedClaims: [] },
  },
];

export const trending = [
  { tag: "₹2000NoteRumour", posts: 3400, language: "Multiple" },
  { tag: "HowrahBridge", posts: 890, language: "বাংলা" },
  { tag: "பள்ளிவிடுமுறை", posts: 12100, language: "தமிழ்" },
  { tag: "LowResourceNLP", posts: 340, language: "English" },
  { tag: "फेकन्यूज़", posts: 2200, language: "हिन्दी" },
];

export const CURRENT_USER_ID = "u6";
